


# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0


# output path to root file
/QPIX/Action/RunAction/root_output /media/ilker/writable/Diffusion/Am241/Am241_1cm.root


/random/setSeeds 0 31

#RegisterDelayed Macro for delaying Nucleous
/QPIX/RegisterDelayedMacro macros/Am241.mac

#GEOMETRY
/Geometry/DiffusionGeometry/world_size 100 cm
/Geometry/DiffusionGeometry/MaterialName GasAr
#/Geometry/DiffusionGeometry/MaterialName LAr
/Geometry/DiffusionGeometry/Pressure 1 bar
/Geometry/DiffusionGeometry/Temperature 293.15 kelvin

## Detector Dimensions
/Geometry/DiffusionGeometry/Det_rmin 0 cm
/Geometry/DiffusionGeometry/Det_rmax 40 cm
/Geometry/DiffusionGeometry/Det_z 12 cm

### Detector Active Area
/Geometry/DiffusionGeometry/DetAct_rmin 0 cm
/Geometry/DiffusionGeometry/DetAct_rmax 3 cm
/Geometry/DiffusionGeometry/DetAct_z 5.5 cm


### Source Holder Dimensions
/Geometry/DiffusionGeometry/HideSourceHolder false
/Geometry/DiffusionGeometry/SourceHolder_rmin 0 cm
/Geometry/DiffusionGeometry/SourceHolder_rmax 0.5 cm
/Geometry/DiffusionGeometry/SourceHolder_z 0.2 cm

#### Position of the Source
/Geometry/DiffusionGeometry/vtx 4 4 5 cm

### Offset for active region
/Geometry/DiffusionGeometry/offset 4 4 4 cm


# GENERATOR
# make unstable isotopes decay at t=0
/Generator/IonGenerator/decay_at_time_zero true  # this is set to false by default

#Am 241
/Generator/IonGenerator/Region detectorActive.logical
/Generator/IonGenerator/AtomicNumber 95
/Generator/IonGenerator/AtomicMass 241

# 1 microcurie --> 37000 Decays/s(Bq)
#/Generator/IonGenerator/DecayRate 1
#/Generator/IonGenerator/EventWindow 1   # seconds
#works only if event_window is zero
#/Generator/IonGenerator/NDecays 39


# Run RTD_Code for Diffusion and Current Profiles
/Actions/EventAction/runRTDCode false

### Variables for Diffusion and Current
#/Actions/RTDManager/Wvalue 23.6
#/Actions/RTDManager/E_vel 164800.0
#/Actions/RTDManager/DiffusionL 6.8223
#/Actions/RTDManager/DiffusionT 13.1586
#/Actions/RTDManager/Life_Time 0.1
#/Actions/RTDManager/Reset 6250
#/Actions/RTDManager/SampleTime 10e-9
#/Actions/RTDManager/BufferTime 100e-6

### Variables for Diffusion and Current in the GAS 50 V/cm
/Actions/RTDManager/Wvalue 26.4 # eV
/Actions/RTDManager/Efield 50 # V/cm
/Actions/RTDManager/Driftz 1 # cm
/Actions/RTDManager/E_vel 200000 # cm/s
/Actions/RTDManager/DiffusionL 1313.31 #cm^2/s
/Actions/RTDManager/DiffusionT 8503.548 #cm^2/s
/Actions/RTDManager/Life_Time 0.1
/Actions/RTDManager/Reset 6250
/Actions/RTDManager/SampleTime 10e-9
/Actions/RTDManager/BufferTime 100e-6
/Actions/RTDManager/SensorPos 2 2 7.5 cm
## When <HideSensors True> Circular traces for detecting electrons will be off
/Actions/RTDManager/HideSensors true
/Actions/RTDManager/NumOfSensors 1
/Actions/RTDManager/SensorSpacing 0.1 cm
/Actions/RTDManager/SensorWidth 0.1 cm
## Creating Pixels instead of circular sensors
/Actions/RTDManager/PixelStepX 6 cm
/Actions/RTDManager/PixelStepY 0.5 cm


