# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0


# output path
/QPIX/Action/RunAction/root_output /media/ilker/writable/QPIX/Am241.root


/random/setSeeds 0 31


#GEOMETRY
/Geometry/DiffusionGeometry/world_size 55 cm
/Geometry/DiffusionGeometry/MaterialName GasAr
#/Geometry/DiffusionGeometry/MaterialName LAr
/Geometry/DiffusionGeometry/Pressure 30 bar
/Geometry/DiffusionGeometry/Temperature 293.15 kelvin

## Detector Dimensions
/Geometry/DiffusionGeometry/Det_rmin 0 cm
/Geometry/DiffusionGeometry/Det_rmax 4.6 cm
/Geometry/DiffusionGeometry/Det_z 10 cm

### Detector Active Area
/Geometry/DiffusionGeometry/DetAct_rmin 0 cm
/Geometry/DiffusionGeometry/DetAct_rmax 4 cm
/Geometry/DiffusionGeometry/DetAct_z 4 cm

### Source Holder Dimensions
/Geometry/DiffusionGeometry/SourceHolder_rmin 0 cm
/Geometry/DiffusionGeometry/SourceHolder_rmax 0.5 cm
/Geometry/DiffusionGeometry/SourceHolder_z 0.2 cm

#### Position of the Source
/Geometry/DiffusionGeometry/vtx 0 0 1 cm

### Offset for active region
/Geometry/DiffusionGeometry/offset 0 0 4 cm



# GENERATOR
# make unstable isotopes decay at t=0
/Generator/DiffusionGenerator/decay_at_time_zero false  # this is set to false by default

#Am 241
/Generator/DiffusionGenerator/Region detectorActive.logical
/Generator/DiffusionGenerator/AtomicNumber 97
/Generator/DiffusionGenerator/AtomicMass 241
# 1 microcurie --> 37000 Decays/s(Bq)
/Generator/DiffusionGenerator/DecayRate 1000
#/Generator/DiffusionGenerator/EventWindow 0
#works only if event_window is zero
#/Generator/DiffusionGenerator/NDecays 39


